### ISSUE TITLE
gulp commands giving an error

### ISSUE THREAD

**Issue by Erscheinung** [kamhix/todoist-linux#38]
gulp start and gulp package aren't working. This is the reported error:

internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/home/USERNAME/Downloads/todoist/todoist-linux/node_modules/natives/index.js:137:5)
    at require (/home/USERNAME/Downloads/todoist/todoist-linux/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/home/USERNAME/Downloads/todoist/todoist-linux/node_modules/natives/index.js:137:5)
    at require (/home/USERNAME/Downloads/todoist/todoist-linux/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/home/USERNAME/Downloads/todoist/todoist-linux/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/USERNAME/Downloads/todoist/todoist-linux/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/USERNAME/Downloads/todoist/todoist-linux/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:99)

**Comment by kamhix** [comment]
It was due to the old gulp package with node recent versions. I have updated the dependencies. Try to pull it and launch npm install again.
